#!/usr/bin/env bash
# Script that sets the port 80
sed -i "s/listen 80 default_server;/" /etc/nginx/sites-enabled/default
sed -i "s/listen \[::\]:80 default_server;/" /etc/nginx/sites-enabled/default
sed -i "s/ ipv4only=on//" /etc/nginx/sites-available/default
service nginx restart
curl 0:80
