#!/usr/bin/env bash
# Script that sets the port 80
sed -i "s/listen 80 default_server;/listen 80;/" /etc/nginx/sites-enabled/default
sed -i "s/listen \[::\]:80 default_server;/listen \[::\]:80;/" /etc/nginx/sites-enabled/default
service nginx restart
